//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.04 at 12:04:02 PM IST 
//


package com.bbb.account.vo.profile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="profileAttributes" type="{}profileDetail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "profileAttributes"
})
@XmlRootElement(name = "userProfile")
public class UserProfile {

    @XmlElement(required = true)
    protected ProfileDetail profileAttributes;

    /**
     * Gets the value of the profileAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileDetail }
     *     
     */
    public ProfileDetail getProfileAttributes() {
        return profileAttributes;
    }

    /**
     * Sets the value of the profileAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileDetail }
     *     
     */
    public void setProfileAttributes(ProfileDetail value) {
        this.profileAttributes = value;
    }

}
