CREATE TABLE FB_USER (
	ID 			VARCHAR2(40)	NOT NULL,
	USER_NAME 		VARCHAR2(254)	NULL,
	NAME 			VARCHAR2(254)	NULL,
	FIRST_NAME 		VARCHAR2(254)	NULL,
	MIDDLE_NAME 		VARCHAR2(254)	NULL,
	LAST_NAME 		VARCHAR2(254)	NULL,
	GENDER 			VARCHAR2(254)	NULL,
	VERIFIED 		NUMBER(1)	NULL,
	OFFLINE_ACCESS_TOKEN 	VARCHAR2(254)	NULL,
	TOKEN_VALID 		NUMBER(1)	NULL,
	CONSTRAINT CK_FB_USER_VRFY CHECK (VERIFIED IN (0, 1)),
	CONSTRAINT CK_FB_USER_TKN CHECK (TOKEN_VALID IN (0, 1)),
	CONSTRAINT PK_FB_USER_ID PRIMARY KEY(ID)
);

CREATE TABLE FB_USER_EDUCATION_ASSOC (
	FB_USER_ID 		VARCHAR2(40)	NOT NULL REFERENCES FB_USER(ID),
	FB_SCHOOL_ID 		INTEGER	NOT NULL,
	CONSTRAINT PK_FB_USER_EDU_ID PRIMARY KEY(FB_USER_ID, FB_SCHOOL_ID)
);

CREATE TABLE FB_USER_FRIEND_ASSOC (
	FB_USER_ID 		VARCHAR2(254)	NOT NULL REFERENCES FB_USER(ID),
	FB_FRIEND_ID 		INTEGER	NOT NULL,
	CONSTRAINT PK_FB_USER_FRN_ID PRIMARY KEY(FB_USER_ID, FB_FRIEND_ID)
);

CREATE TABLE FB_SCHOOL (
	ID 			VARCHAR2(254)	NOT NULL,
	SCHOOL_ID		VARCHAR2(254)	NULL,
	NAME 			VARCHAR2(254)	NULL,
	CONSTRAINT PK_FB_SCL_ID PRIMARY KEY(ID)
);


CREATE TABLE FB_BBB_USER_ASSOC (
	BBB_USER_ID 		VARCHAR2(254)	NOT NULL REFERENCES DPS_USER(ID),
	FB_USER_ID 		VARCHAR2(254)	NULL REFERENCES FB_USER(ID),
	CONSTRAINT PK_FB_BBB_USER_ID PRIMARY KEY(BBB_USER_ID)
);