SET DEFINE OFF;
 
 ALTER TABLE BBB_POPULAR_ITEMS  ADD   QUERY_TITLE VARCHAR2(40) NULL;
 
 ALTER TABLE BBB_POPULAR_ITEMS  ADD  SITE_ID VARCHAR2(40) NULL;
  
 ALTER TABLE BBB_POPULAR_ITEMS  ADD CONSTRAINT   FK_BBB_POPULAR_ITEMS FOREIGN KEY(SITE_ID) REFERENCES SITE_CONFIGURATION(ID) ;
 
 ALTER TABLE BBB_POPULAR_ITEMS  ADD  RESULT_SIZE INTEGER  NULL ;

COMMIT;
