SET DEFINE OFF;
 
 ALTER TABLE BBB_POPULAR_ITEMS  ADD COLUMN  QUERY_TITLE VARCHAR2(40) NULL;
 
 ALTER TABLE BBB_POPULAR_ITEMS  ADD COLUMN SITE_ID VARCHAR2(40) NULL;
 
 ALTER TABLE BBB_POPULAR_ITEMS  ADD  RESULT_SIZE INTEGER  NULL ;
 
COMMIT;