SET DEFINE OFF;

CREATE TABLE BBB_KICK_STARTER (
 	id varchar2(40) NOT NULL,
 	heading1 varchar2(254) NOT NULL,
 	heading2 varchar2(254) NULL, 
 	description varchar2(2000) NULL, 
 	image_url varchar2(254) NULL,
 	hero_image_url varchar2(254) NULL,
 	priority INTEGER NULL, 
	is_active INTEGER NULL, 
 	kick_starter_type INTEGER NULL); 
    
ALTER TABLE BBB_KICK_STARTER ADD CONSTRAINT PK_BBB_KICK_STARTER PRIMARY KEY (id) USING INDEX TABLESPACE INDX01;

    
CREATE TABLE BBB_PICKLIST_SKU_ITEM (
	id varchar2(40) NOT NULL,
	sku_id varchar2(40) NOT NULL,
	recommended_qty INTEGER NOT NULL,
	sku_comment  varchar2(1000) NULL );	
	
ALTER TABLE BBB_PICKLIST_SKU_ITEM  ADD CONSTRAINT PK_BBB_PICKLIST_SKU_ITEM  PRIMARY KEY (id) USING INDEX TABLESPACE INDX01;
	
 CREATE TABLE BBB_KICK_START_REG_TYPE_BADGE ( 
 	id varchar2(40) NOT NULL, 
 	registry_type varchar2(254) NOT NULL , 
 	registry_image_url varchar2(254) NULL);	

ALTER TABLE BBB_KICK_START_REG_TYPE_BADGE  ADD CONSTRAINT PK_BBB_KICK_START_REG_TYPE_BE   PRIMARY KEY (id) USING INDEX TABLESPACE INDX01;

ALTER TABLE BBB_KICK_START_REG_TYPE_BADGE  ADD CONSTRAINT FK_BBB_KICK_START_REG_TYPE_BE  FOREIGN KEY(registry_type) REFERENCES BBB_REGISTRY_TYPE(registry_type_id) ;
	
 CREATE TABLE BBB_KICK_STARTER_PICKLIST ( 
	id varchar2(40) NOT NULL, 
	picklist_title varchar2(254) NULL,
	picklist_summary_description varchar2(1000) NULL,
	customer_type INTEGER NULL, 
	site_id varchar2(40) NULL );
	
ALTER TABLE BBB_KICK_STARTER_PICKLIST  ADD CONSTRAINT PK_BBB_KICK_STARTER_PICKLIST   PRIMARY KEY (id) USING INDEX TABLESPACE INDX01;

ALTER TABLE BBB_KICK_STARTER_PICKLIST  ADD CONSTRAINT   FK_BBB_KICK_STARTER_PICKLIST FOREIGN KEY(site_id) REFERENCES SITE_CONFIGURATION(id) ;
 	
CREATE TABLE BBB_KICK_STARTER_PICKLISTS (
 	id varchar2(40) NOT NULL ,
 	kick_starter_picklist_id varchar2(40) NULL 
 	);
 	
CREATE INDEX BBB_KICK_STARTER_PICKLISTS_IDX  ON BBB_KICK_STARTER_PICKLISTS(kick_starter_picklist_id,id)  ;

ALTER TABLE BBB_KICK_STARTER_PICKLISTS  ADD CONSTRAINT PK_BBB_KICK_STARTER_PICKLISTS PRIMARY KEY (id, kick_starter_picklist_id) USING INDEX TABLESPACE INDX01;

ALTER TABLE BBB_KICK_STARTER_PICKLISTS  ADD CONSTRAINT FK_BBB_KICK_STARTER_PICKLISTS FOREIGN KEY(kick_starter_picklist_id) REFERENCES BBB_KICK_STARTER_PICKLIST(id);

ALTER TABLE BBB_KICK_STARTER_PICKLISTS  ADD CONSTRAINT FK_BBB_KICK_STARTER_PICKLISTSD FOREIGN KEY(id) REFERENCES BBB_KICK_STARTER(id);




 	 
CREATE TABLE BBB_PICKLIST_REG_TYPES (
	id varchar2(40) NOT NULL ,
	registry_type_id varchar2(40) NULL 
 ); 
	
CREATE INDEX BBB_PICKLIST_REG_TYPES_IDX ON BBB_PICKLIST_REG_TYPES(registry_type_id , id);

ALTER TABLE BBB_PICKLIST_REG_TYPES  ADD CONSTRAINT PK_BBB_PICKLIST_REG_TYPES PRIMARY KEY(id, registry_type_id) USING INDEX TABLESPACE INDX01;

ALTER TABLE BBB_PICKLIST_REG_TYPES  ADD CONSTRAINT  FK_BBB_PICKLIST_REG_TYPES_ID FOREIGN KEY(id) REFERENCES BBB_KICK_STARTER_PICKLIST(id) ;

ALTER TABLE BBB_PICKLIST_REG_TYPES  ADD CONSTRAINT FK_BBB_PICKLIST_REG_TYPES_RID FOREIGN KEY(registry_type_id) REFERENCES BBB_KICK_START_REG_TYPE_BADGE(id);

 
CREATE TABLE BBB_PICKLIST_CHANNELS (
    id varchar2(40) NOT NULL , 
    channels_id varchar2(40) NULL   );

CREATE INDEX BBB_PICKLIST_CHANNELS_IDX ON BBB_PICKLIST_CHANNELS(channels_id , id) ;

ALTER TABLE BBB_PICKLIST_CHANNELS  ADD CONSTRAINT PK_BBB_PICKLIST_CHANNELS PRIMARY KEY(id, channels_id) USING INDEX TABLESPACE INDX01;

ALTER TABLE BBB_PICKLIST_CHANNELS  ADD CONSTRAINT  FK_BBB_PICKLIST_CHANNELS_ID FOREIGN KEY(id) REFERENCES BBB_KICK_STARTER_PICKLIST(id) ;

ALTER TABLE BBB_PICKLIST_CHANNELS  ADD CONSTRAINT FK_BBB_PICKLIST_CHANNELS_CHID FOREIGN KEY(channels_id) REFERENCES BBB_CHANNEL_INFO(CHANNEL_ID);

CREATE TABLE BBB_PICKLIST_SKUS ( 
	id varchar2(40) NOT NULL ,
	sequence_num INTEGER NOT NULL, 
	sku_id varchar2(40) NOT NULL ); 
	
CREATE INDEX BBB_PICKLIST_SKUS_IDX  ON BBB_PICKLIST_SKUS(sequence_num , id);

ALTER TABLE BBB_PICKLIST_SKUS ADD CONSTRAINT PK_BBB_PICKLIST_SKUS PRIMARY KEY(id, sequence_num) USING INDEX TABLESPACE INDX01 ;

ALTER TABLE BBB_PICKLIST_SKUS ADD CONSTRAINT FK_BBB_PICKLIST_SKUS_ID FOREIGN KEY(id) REFERENCES BBB_KICK_STARTER_PICKLIST(id) ;

ALTER TABLE BBB_PICKLIST_SKUS ADD CONSTRAINT FK_BBB_PICKLIST_SKUS_SKUID FOREIGN KEY(sku_id) REFERENCES BBB_PICKLIST_SKU_ITEM(id);
	
COMMIT;