SET DEFINE OFF;
 	 
CREATE TABLE BBB_POPULAR_ITEMS (
	id varchar2(40) NOT NULL ,
	search_query varchar2(500) NULL
	
 ); 
 
ALTER TABLE BBB_POPULAR_ITEMS  ADD CONSTRAINT PK_BBB_POPULAR_ITEMS PRIMARY KEY(id) USING INDEX TABLESPACE INDX01;


CREATE TABLE BBB_POPULAR_ITEMS_REG_TYS (
    id varchar2(40) NOT NULL , 
    registry_type varchar2(40) NULL   );

CREATE INDEX BBB_POPULAR_ITEMS_REG_TYS_IDX ON BBB_POPULAR_ITEMS_REG_TYS(registry_type , id) ;

ALTER TABLE BBB_POPULAR_ITEMS_REG_TYS  ADD CONSTRAINT PK_BBB_POPULAR_ITEMS_REG_TYS PRIMARY KEY(id, registry_type) USING INDEX TABLESPACE INDX01;

ALTER TABLE BBB_POPULAR_ITEMS_REG_TYS  ADD CONSTRAINT  FK_BBB_POPULAR_ITEMS_REG_TYS FOREIGN KEY(id) REFERENCES BBB_POPULAR_ITEMS(id) ;

ALTER TABLE BBB_POPULAR_ITEMS_REG_TYS  ADD CONSTRAINT FK_BBB_POPULAR_ITEMS_REG_TYS_R FOREIGN KEY(registry_type) REFERENCES BBB_REGISTRY_TYPE(registry_type_id);

	
COMMIT;