CREATE TABLE BBB_INVENTORY
  (
    INVENTORY_ID VARCHAR2(40),
    ALT_AFS      NUMBER(10,0) DEFAULT 0,
    IGR          NUMBER(10,0) DEFAULT 0,
    CONSTRAINT PK_BBB_INV_INV_ID PRIMARY KEY(INVENTORY_ID),
    CONSTRAINT FK_BBB_INV_INV_ID FOREIGN KEY(INVENTORY_ID) REFERENCES DCS_INVENTORY(INVENTORY_ID)
  );
  
CREATE TABLE BBB_INVENTORY_TRANSLATION
  (
    TRANSLATION_ID VARCHAR2(40),
    SITE_ID        VARCHAR2(40),
    ALT_AFS        NUMBER(10,0) DEFAULT 0,
    IGR            NUMBER(10,0) DEFAULT 0,
    CONSTRAINT PK_BBB_INV_TRS_TRS_ID_SIT_ID PRIMARY KEY(TRANSLATION_ID, SITE_ID)
  );   


CREATE TABLE BBB_INVENTORY_SITE_TRANSLATION (
	INVENTORY_ID VARCHAR2(40) NOT NULL,
	TRANSLATION_ID 		INTEGER	NOT NULL,
	CONSTRAINT PK_BBB_INV_SIT_TRS PRIMARY KEY(INVENTORY_ID, TRANSLATION_ID),
	CONSTRAINT FK_BBB_INV_SIT_TRS_INV_ID FOREIGN KEY(INVENTORY_ID) REFERENCES DCS_INVENTORY(INVENTORY_ID)
);

CREATE TABLE BBB_INVENTORY_FEED
  (
    FEED_ID VARCHAR2(40),
    SITE_ID       VARCHAR2(40),
    INVENTORY_ID       VARCHAR2(40),
    CREATION_DATE      TIMESTAMP DEFAULT SYSDATE,
    FEED_STATUS        VARCHAR2(20),
    LAST_UPDATED       TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT PK_BBB_INV_FED PRIMARY KEY(FEED_ID, SITE_ID, INVENTORY_ID),
    CONSTRAINT FK_BBB_INV_FED_SKU_ID FOREIGN KEY(INVENTORY_ID) REFERENCES DCS_INVENTORY(INVENTORY_ID)
  ); 
