SET ECHO ON;
SET DEFINE OFF;

ALTER TABLE BBB_CORE.TBS_ITEM_INFO_DETAILS ADD tbs_override_quantity number(10);

CREATE TABLE BBB_CORE.TBS_GS_ORDER_INFO (
	GSORDER_ID 		VARCHAR2(254)	NOT NULL,
	USER_TOKEN 		VARCHAR2(254)	NULL,
	STORE_ID 		INTEGER			NULL,
	TERMINAL_ID 	INTEGER			NULL,
	RE_LAST_NM 		VARCHAR2(254)	NULL,
	RE_FIRST_NM 	VARCHAR2(254)	NULL,
	RE_EMAIL 		VARCHAR2(254)	NULL,
	RE_PHONE 		VARCHAR2(254)	NULL,
	SKUS 			VARCHAR2(254)	NULL,
	QUANTITIES 		VARCHAR2(254)	NULL,
	REGISTRY_ID 	VARCHAR2(254)	NULL,
	PRIMARY KEY(GSORDER_ID)
);

alter table BBB_CORE.bbb_order add tbs_store_no varchar2(20) null;