SET ECHO ON;
SET DEFINE OFF;

ALTER TABLE BBB_CORE_PRV.BBB_HOMEPAGE_CATEGORY DROP CONSTRAINT BBB_HOMEPAGE_CATEGORY_PK;
DROP INDEX BBB_CORE_PRV.BBB_HOMEPAGE_CATEGORY_PK;
ALTER TABLE BBB_CORE_PRV.BBB_HOMEPAGE_CATEGORY ADD CONSTRAINT BBB_HOMEPAGE_CATEGORY_PK PRIMARY KEY (HOMEPAGE_TEMPLATE_ID, SEQUENCE_NUM);
ALTER TABLE BBB_CORE_PRV.BBB_HOMEPAGE_TEMPLATE ADD CONSTRAINT BBB_HOMEPAGE_TEMPLATE_PK PRIMARY KEY (homepage_template_id);
ALTER TABLE BBB_CORE_PRV.BBB_CATEGORY_CONTAINER ADD CONSTRAINT BBB_CATEGORY_CONTAINER_PK PRIMARY KEY (cat_container_id);

alter table BBB_CORE_PRV.BBB_HOMEPAGE_TEMPLATE add (
  logo_image VARCHAR2(40) NULL, 
  use_announcement_fromweb NUMBER(1) default 1,
  announcement VARCHAR2(40) NULL,
  use_popular_cat_fromweb NUMBER(1) default 1,
  use_featured_cat_fromweb NUMBER(1) default 1,
  use_promoregpanel_fromweb NUMBER(1) default 1,
  use_promotierlayout1_fromweb NUMBER(1) default 1
);

create table BBB_CORE_PRV.BBB_HOMEPAGE_FEAT_CATEGORY(
   homepage_template_id VARCHAR2(40) NOT NULL, 
   sequence_num NUMBER NOT NULL,
   cat_container_id VARCHAR2(40) NOT NULL,
   CONSTRAINT BBB_HP_FEAT_CAT_PK PRIMARY KEY (homepage_template_id, sequence_num),
   CONSTRAINT BBB_HP_FEAT_CAT_FK1 FOREIGN KEY (homepage_template_id) REFERENCES BBB_CORE_PRV.BBB_HOMEPAGE_TEMPLATE (homepage_template_id), 
   CONSTRAINT BBB_HP_FEAT_CAT_FK2 FOREIGN KEY (cat_container_id) REFERENCES BBB_CORE_PRV.BBB_CATEGORY_CONTAINER (cat_container_id)
);

ALTER TABLE BBB_CORE_PRV.TBS_ITEM_INFO_DETAILS ADD tbs_override_quantity number(10);


CREATE TABLE BBB_CORE_PRV.TBS_GS_ORDER_INFO (
	GSORDER_ID 		VARCHAR2(254)	NOT NULL,
	USER_TOKEN 		VARCHAR2(254)	NULL,
	STORE_ID 		INTEGER			NULL,
	TERMINAL_ID 	INTEGER			NULL,
	RE_LAST_NM 		VARCHAR2(254)	NULL,
	RE_FIRST_NM 	VARCHAR2(254)	NULL,
	RE_EMAIL 		VARCHAR2(254)	NULL,
	RE_PHONE 		VARCHAR2(254)	NULL,
	SKUS 			VARCHAR2(254)	NULL,
	QUANTITIES 		VARCHAR2(254)	NULL,
	REGISTRY_ID 	VARCHAR2(254)	NULL,
	PRIMARY KEY(GSORDER_ID)
);


alter table BBB_CORE_PRV.bbb_order add tbs_store_no varchar2(20) null;


