-- DROP TABLE TBS_GS_ORDER_INFO;

CREATE TABLE TBS_GS_ORDER_INFO (
	GSORDER_ID 		VARCHAR2(254)	NOT NULL,
	USER_TOKEN 		VARCHAR2(254)	NULL,
	STORE_ID 		INTEGER			NULL,
	TERMINAL_ID 	INTEGER			NULL,
	RE_LAST_NM 		VARCHAR2(254)	NULL,
	RE_FIRST_NM 	VARCHAR2(254)	NULL,
	RE_EMAIL 		VARCHAR2(254)	NULL,
	RE_PHONE 		VARCHAR2(254)	NULL,
	SKUS 			VARCHAR2(254)	NULL,
	QUANTITIES 		VARCHAR2(254)	NULL,
	REGISTRY_ID 	VARCHAR2(254)	NULL,
	PRIMARY KEY(GSORDER_ID)
);