

CREATE TABLE BBB_LBL_TXT (
	LBL_TXT_ID 		varchar2(40)	NOT NULL,
	KEY 			varchar2(254)	NULL,
	LANGUAGE 		INTEGER	NULL,
	TEMPLATE_TYPE 		INTEGER	NULL,
	LABEL_VALUE 		varchar2(1000)	NULL,
	TEXTAREA_VALUE 		varchar2(4000)	NULL,
	ERROR_MSG 		varchar2(1000)	NULL,
	PRIMARY KEY(LBL_TXT_ID)
);

CREATE TABLE BBB_LBL_TXT_TRANSLATIONS (
	translation_id 		varchar2(40)	NOT NULL,
	LABEL_VALUE 		varchar2(1000)	NULL,
	TEXTAREA_VALUE 		varchar2(4000)	NULL,
	ERROR_MSG 		varchar2(1000)	NULL,
	PRIMARY KEY(translation_id)
);

CREATE TABLE BBB_LBL_TXT_SITE_TRANSLATIONS (
	LBL_TXT_ID 		varchar2(40)	NOT NULL REFERENCES BBB_LBL_TXT(LBL_TXT_ID),
	site_id 		varchar2(40)	NOT NULL,
	translation_id 		varchar2(40)	NULL REFERENCES BBB_LBL_TXT_TRANSLATIONS(translation_id),
	PRIMARY KEY(LBL_TXT_ID, site_id)
);

 


