//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.16 at 04:29:01 PM IST 
//


package com.bbb.bopus.inventory.output;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Item" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Facility" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Segment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Segmentation_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Manufacturing_Date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Lot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Total_Inventory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Total_On_Hand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Total_Future" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Total_Supply_Balance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Total_Allocated_Qty_Onhand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Total_Allocated_Qty_Future" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Total_Unallocatable_Qty" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="On_Hand_Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Inventory_Watermark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UOM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="From_Date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="To_Date" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}Future_Supply" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}Error_List" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item",
    "facility",
    "segment",
    "segmentationType",
    "manufacturingDate",
    "lot",
    "totalInventory",
    "totalOnHand",
    "totalFuture",
    "totalSupplyBalance",
    "totalAllocatedQtyOnhand",
    "totalAllocatedQtyFuture",
    "totalUnallocatableQty",
    "onHandStatus",
    "inventoryWatermark",
    "uom",
    "fromDate",
    "toDate",
    "futureSupply",
    "errorList"
})
@XmlRootElement(name = "Line_Item")
public class LineItem {

    @XmlElement(name = "Item", required = true)
    protected String item;
    @XmlElement(name = "Facility")
    protected String facility;
    @XmlElement(name = "Segment")
    protected String segment;
    @XmlElement(name = "Segmentation_Type")
    protected String segmentationType;
    @XmlElement(name = "Manufacturing_Date")
    protected String manufacturingDate;
    @XmlElement(name = "Lot")
    protected String lot;
    @XmlElement(name = "Total_Inventory", required = true)
    protected String totalInventory;
    @XmlElement(name = "Total_On_Hand", required = true)
    protected String totalOnHand;
    @XmlElement(name = "Total_Future", required = true)
    protected String totalFuture;
    @XmlElement(name = "Total_Supply_Balance", required = true)
    protected String totalSupplyBalance;
    @XmlElement(name = "Total_Allocated_Qty_Onhand", required = true)
    protected String totalAllocatedQtyOnhand;
    @XmlElement(name = "Total_Allocated_Qty_Future", required = true)
    protected String totalAllocatedQtyFuture;
    @XmlElement(name = "Total_Unallocatable_Qty", required = true)
    protected String totalUnallocatableQty;
    @XmlElement(name = "On_Hand_Status")
    protected String onHandStatus;
    @XmlElement(name = "Inventory_Watermark")
    protected String inventoryWatermark;
    @XmlElement(name = "UOM")
    protected String uom;
    @XmlElement(name = "From_Date")
    protected String fromDate;
    @XmlElement(name = "To_Date")
    protected String toDate;
    @XmlElement(name = "Future_Supply")
    protected List<FutureSupply> futureSupply;
    @XmlElement(name = "Error_List")
    protected ErrorList errorList;

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItem(String value) {
        this.item = value;
    }

    /**
     * Gets the value of the facility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacility() {
        return facility;
    }

    /**
     * Sets the value of the facility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacility(String value) {
        this.facility = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegment(String value) {
        this.segment = value;
    }

    /**
     * Gets the value of the segmentationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentationType() {
        return segmentationType;
    }

    /**
     * Sets the value of the segmentationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentationType(String value) {
        this.segmentationType = value;
    }

    /**
     * Gets the value of the manufacturingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturingDate() {
        return manufacturingDate;
    }

    /**
     * Sets the value of the manufacturingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturingDate(String value) {
        this.manufacturingDate = value;
    }

    /**
     * Gets the value of the lot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLot() {
        return lot;
    }

    /**
     * Sets the value of the lot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLot(String value) {
        this.lot = value;
    }

    /**
     * Gets the value of the totalInventory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalInventory() {
        return totalInventory;
    }

    /**
     * Sets the value of the totalInventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalInventory(String value) {
        this.totalInventory = value;
    }

    /**
     * Gets the value of the totalOnHand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalOnHand() {
        return totalOnHand;
    }

    /**
     * Sets the value of the totalOnHand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalOnHand(String value) {
        this.totalOnHand = value;
    }

    /**
     * Gets the value of the totalFuture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalFuture() {
        return totalFuture;
    }

    /**
     * Sets the value of the totalFuture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalFuture(String value) {
        this.totalFuture = value;
    }

    /**
     * Gets the value of the totalSupplyBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalSupplyBalance() {
        return totalSupplyBalance;
    }

    /**
     * Sets the value of the totalSupplyBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalSupplyBalance(String value) {
        this.totalSupplyBalance = value;
    }

    /**
     * Gets the value of the totalAllocatedQtyOnhand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalAllocatedQtyOnhand() {
        return totalAllocatedQtyOnhand;
    }

    /**
     * Sets the value of the totalAllocatedQtyOnhand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalAllocatedQtyOnhand(String value) {
        this.totalAllocatedQtyOnhand = value;
    }

    /**
     * Gets the value of the totalAllocatedQtyFuture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalAllocatedQtyFuture() {
        return totalAllocatedQtyFuture;
    }

    /**
     * Sets the value of the totalAllocatedQtyFuture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalAllocatedQtyFuture(String value) {
        this.totalAllocatedQtyFuture = value;
    }

    /**
     * Gets the value of the totalUnallocatableQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalUnallocatableQty() {
        return totalUnallocatableQty;
    }

    /**
     * Sets the value of the totalUnallocatableQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalUnallocatableQty(String value) {
        this.totalUnallocatableQty = value;
    }

    /**
     * Gets the value of the onHandStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnHandStatus() {
        return onHandStatus;
    }

    /**
     * Sets the value of the onHandStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnHandStatus(String value) {
        this.onHandStatus = value;
    }

    /**
     * Gets the value of the inventoryWatermark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryWatermark() {
        return inventoryWatermark;
    }

    /**
     * Sets the value of the inventoryWatermark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryWatermark(String value) {
        this.inventoryWatermark = value;
    }

    /**
     * Gets the value of the uom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUOM() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUOM(String value) {
        this.uom = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromDate(String value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToDate(String value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the futureSupply property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the futureSupply property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFutureSupply().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FutureSupply }
     * 
     * 
     */
    public List<FutureSupply> getFutureSupply() {
        if (futureSupply == null) {
            futureSupply = new ArrayList<FutureSupply>();
        }
        return this.futureSupply;
    }

    /**
     * Gets the value of the errorList property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorList }
     *     
     */
    public ErrorList getErrorList() {
        return errorList;
    }

    /**
     * Sets the value of the errorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorList }
     *     
     */
    public void setErrorList(ErrorList value) {
        this.errorList = value;
    }

}
