//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.16 at 04:29:01 PM IST 
//


package com.bbb.bopus.inventory.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SupplyBalanceOutput"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "supplyBalanceOutput"
})
@XmlRootElement(name = "Message")
public class Message {

    @XmlElement(name = "SupplyBalanceOutput", required = true)
    protected SupplyBalanceOutput supplyBalanceOutput;

    /**
     * Gets the value of the supplyBalanceOutput property.
     * 
     * @return
     *     possible object is
     *     {@link SupplyBalanceOutput }
     *     
     */
    public SupplyBalanceOutput getSupplyBalanceOutput() {
        return supplyBalanceOutput;
    }

    /**
     * Sets the value of the supplyBalanceOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplyBalanceOutput }
     *     
     */
    public void setSupplyBalanceOutput(SupplyBalanceOutput value) {
        this.supplyBalanceOutput = value;
    }

}
