//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.16 at 04:29:01 PM IST 
//


package com.bbb.bopus.inventory.output;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bbb.bopus.inventory.output package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bbb.bopus.inventory.output
     * 
     */
    public ObjectFactory() {
    	//default constructor
    }

    /**
     * Create an instance of {@link TXML }
     * 
     */
    public TXML createTXML() {
        return new TXML();
    }

    /**
     * Create an instance of {@link ErrorList }
     * 
     */
    public ErrorList createErrorList() {
        return new ErrorList();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    // Added NOPMD since this is not JAVA Error as suggested by PMD rule. It's a custom class, PMD error came because of name Error.
    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();// NOPMD
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link LineItem }
     * 
     */
    public LineItem createLineItem() {
        return new LineItem();
    }

    /**
     * Create an instance of {@link FutureSupply }
     * 
     */
    public FutureSupply createFutureSupply() {
        return new FutureSupply();
    }

    /**
     * Create an instance of {@link ViewByFacility }
     * 
     */
    public ViewByFacility createViewByFacility() {
        return new ViewByFacility();
    }

    /**
     * Create an instance of {@link ViewByNetwork }
     * 
     */
    public ViewByNetwork createViewByNetwork() {
        return new ViewByNetwork();
    }

    /**
     * Create an instance of {@link ViewBySegment }
     * 
     */
    public ViewBySegment createViewBySegment() {
        return new ViewBySegment();
    }

    /**
     * Create an instance of {@link SupplyBalanceOutput }
     * 
     */
    public SupplyBalanceOutput createSupplyBalanceOutput() {
        return new SupplyBalanceOutput();
    }

}
