//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.16 at 04:29:01 PM IST 
//


package com.bbb.bopus.inventory.output;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Action_Type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Alert_Level" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Alert_Quantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}View_By_Facility" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}View_By_Network" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}View_By_Segment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "actionType",
    "alertLevel",
    "alertQuantity",
    "viewByFacility",
    "viewByNetwork",
    "viewBySegment"
})
@XmlRootElement(name = "SupplyBalanceOutput")
public class SupplyBalanceOutput {

    @XmlElement(name = "Action_Type")
    protected String actionType;
    @XmlElement(name = "Alert_Level")
    protected String alertLevel;
    @XmlElement(name = "Alert_Quantity")
    protected String alertQuantity;
    @XmlElement(name = "View_By_Facility")
    protected List<ViewByFacility> viewByFacility;
    @XmlElement(name = "View_By_Network")
    protected List<ViewByNetwork> viewByNetwork;
    @XmlElement(name = "View_By_Segment")
    protected List<ViewBySegment> viewBySegment;

    /**
     * Gets the value of the actionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionType(String value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the alertLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertLevel() {
        return alertLevel;
    }

    /**
     * Sets the value of the alertLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertLevel(String value) {
        this.alertLevel = value;
    }

    /**
     * Gets the value of the alertQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertQuantity() {
        return alertQuantity;
    }

    /**
     * Sets the value of the alertQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertQuantity(String value) {
        this.alertQuantity = value;
    }

    /**
     * Gets the value of the viewByFacility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viewByFacility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViewByFacility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ViewByFacility }
     * 
     * 
     */
    public List<ViewByFacility> getViewByFacility() {
        if (viewByFacility == null) {
            viewByFacility = new ArrayList<ViewByFacility>();
        }
        return this.viewByFacility;
    }

    /**
     * Gets the value of the viewByNetwork property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viewByNetwork property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViewByNetwork().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ViewByNetwork }
     * 
     * 
     */
    public List<ViewByNetwork> getViewByNetwork() {
        if (viewByNetwork == null) {
            viewByNetwork = new ArrayList<ViewByNetwork>();
        }
        return this.viewByNetwork;
    }

    /**
     * Gets the value of the viewBySegment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the viewBySegment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getViewBySegment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ViewBySegment }
     * 
     * 
     */
    public List<ViewBySegment> getViewBySegment() {
        if (viewBySegment == null) {
            viewBySegment = new ArrayList<ViewBySegment>();
        }
        return this.viewBySegment;
    }

}
