-- To be executed in the BBB_PIM_STG schema

CREATE TABLE ECP_DIRECT_FEED_MONITORING (	
	FEED_ID			 NUMBER(10,0), 
	FEED_STATUS		 VARCHAR2(100 BYTE)
   ) ;

ALTER TABLE ECP_DIRECT_FEED_MONITORING
ADD CONSTRAINT "ECP_DIRECT_FEED_MONITORIN_PK" PRIMARY KEY (FEED_ID);

ALTER TABLE ECP_DIRECT_FEED_MONITORING 
ADD CONSTRAINT "ECP_DIRECT_FEED_MONITORIN_FK1" FOREIGN KEY (FEED_ID) 
REFERENCES ECP_FEED_MONITORING ("FEED_ID") ON DELETE CASCADE ENABLE;

