-- To be executed in the BBB_PIM_STG schema

ALTER TABLE BBB_PIM_STG.ECP_FEED_MONITORING MODIFY FEED_TYPE VARCHAR2(20);

CREATE TABLE BBB_PIM_STG.ECP_PRJ_IMPORTED_FEEDS(
PROJECT_ID VARCHAR2(40),
FEED_ID NUMBER(10,0),
PROJECT_NAME VARCHAR2(1024),
IMPORTED_TIME TIMESTAMP,
DEPLOYED_TIME TIMESTAMP,
CONSTRAINT ECP_PRJ_IMPORTED_FEEDS_PK PRIMARY KEY (PROJECT_ID, FEED_ID),
CONSTRAINT ECP_PRJ_IMPORTED_FEEDS_FK FOREIGN KEY (FEED_ID) REFERENCES BBB_PIM_STG.ECP_FEED_MONITORING (FEED_ID));

CREATE INDEX BBB_PIM_STG.ECP_PRJ_IMPORTED_FEEDS_IDX ON BBB_PIM_STG.ECP_PRJ_IMPORTED_FEEDS (PROJECT_ID);