-- To be executed in the BBB_PIM_STG schema

CREATE TABLE BBB_PIM_STG.ECP_FEED_TIME_DETAILS (
	FEED_ID NUMBER,
	RUN_ID NUMBER,
	TABLE_PROCESSED VARCHAR2(50) NOT NULL,
	NO_OF_ROWS NUMBER NOT NULL,
	START_TIME TIMESTAMP  NOT NULL,
	END_TIME TIMESTAMP  NOT NULL,
	IS_PROD_IMPORT NUMBER NOT NULL,
	CONSTRAINT ECP_FEED_TIME_DETAILS_PK PRIMARY KEY (FEED_ID, RUN_ID),
	CONSTRAINT ECP_FEED_TIME_DETAILS_ECP_FK FOREIGN KEY (FEED_ID) REFERENCES BBB_PIM_STG.ECP_FEED_MONITORING (FEED_ID));

CREATE INDEX BBB_PIM_STG.ECP_TIME_DETS_TBL_PR_IDX ON BBB_PIM_STG.ECP_FEED_TIME_DETAILS (TABLE_PROCESSED);
CREATE INDEX BBB_PIM_STG.ECP_TIME_DETS_PRD_IMP_IDX ON BBB_PIM_STG.ECP_FEED_TIME_DETAILS (IS_PROD_IMPORT);

CREATE SEQUENCE BBB_PIM_STG.ECP_TIME_DETAILS_SEQ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE;

CREATE OR REPLACE TRIGGER BBB_PIM_STG.ECP_FEED_TIME_DETAILS_TRIGGER 
BEFORE INSERT ON BBB_PIM_STG.ECP_FEED_TIME_DETAILS 
FOR EACH ROW 
BEGIN
  SELECT BBB_PIM_STG.ECP_TIME_DETAILS_SEQ.NEXTVAL INTO :NEW.RUN_ID FROM DUAL;
END;
/