CREATE TABLE ECP_FEED_MONITORING( 
     FEED_ID NUMBER(10)  NOT NULL , 
     "DATE" DATE, 
     FEED_TYPE VARCHAR2(10) , 
     FEED_STATUS VARCHAR2(20) , 
     SCHEDULE_DATE DATE 
);

CREATE TABLE ECP_ITEMS_FREQUENT ( 
     FEED_ID NUMBER(10)  NOT NULL , 
     SKU_ID NUMBER(9)  NOT NULL , 
     WEB_OFFERED_FLAG CHAR(1) , 
     BAB_WEB_OFFERED_FLAG CHAR(1) , 
     CA_WEB_OFFERED_FLAG CHAR(1) , 
     DISABLE_FLAG CHAR(1) , 
     BAB_DISABLE_FLAG CHAR(1) , 
     CA_DISABLE_FLAG CHAR(1) ,
     COLLECTION_FLAG CHAR(1), 
     PRODUCT_FLAG CHAR(1),
     LEAD_PROD_FLAG CHAR(1),
     PRODUCT_TITLE VARCHAR2(100) , 
     CA_PRODUCT_TITLE VARCHAR2(50) , 
     BAB_PRODUCT_TITLE VARCHAR2(50) , 
     SHORT_DESCRIPTION VARCHAR2(200) , 
     CA_SHORT_DESCRIPTION VARCHAR2(200) , 
     BAB_SHORT_DESCRIPTION VARCHAR2(200) , 
     WEB_DESCRIP VARCHAR2(2000) , 
     CA_WEB_DESCRIP VARCHAR2(2000) , 
     BAB_WEB_DESCRIP VARCHAR2(2000) , 
     PRICE_RANGE_DESCRIP VARCHAR2(50) , 
     CA_PRICE_RANGE_DESCRIP VARCHAR2(50) , 
     SKU_LOW_PRICE NUMBER(9), 
     CA_SKU_LOW_PRICE NUMBER(9), 
     SKU_HIGH_PRICE NUMBER(9), 
     CA_SKU_HIGH_PRICE NUMBER(9), 
     SHOW_IMAGES_COLLECTION CHAR(1), 
     SHIPPING_SURCHARGE NUMBER(10,2) , 
     CA_SHIPPING_SURCHARGE NUMBER(10,2) , 
     BAB_SHIPPING_SURCHARGE NUMBER(10,2),
     BOPUS_EXCLUSION_FLAG CHAR(1)
);

ALTER TABLE ECP_ITEMS_FREQUENT 
    ADD CONSTRAINT ECP_ITEMS_FREQ_PK PRIMARY KEY ( FEED_ID, SKU_ID ) ;

ALTER TABLE ECP_ITEMS_FREQUENT 
    ADD CONSTRAINT ECP_ITEMS_FREQUENT_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_ITEMS_RARE 
    ( 
     FEED_ID NUMBER(10)  NOT NULL , 
     SKU_ID NUMBER(9)  NOT NULL , 
     COLOR VARCHAR2(50) , 
     COLOR_GROUP VARCHAR2(50) , 
     COST NUMBER(12,2) , 
     CA_COST NUMBER(12,2) , 
     "SIZE" VARCHAR2(50) , 
     IMG_SMALL_LOC VARCHAR2(100), 
     IMG_MED_LOC VARCHAR2(100), 
     IMG_LARGE_LOC VARCHAR2(100), 
     IMG_SWATCH_LOC VARCHAR2(100), 
     IMG_ZOOM_LOC VARCHAR2(100), 
     IMG_ZOOM_INDEX VARCHAR2(100), 
     COLLECTION_FLAG CHAR(1), 
     PRODUCT_FLAG CHAR(1),
     LEAD_PROD_FLAG CHAR(1),
     WEB_ONLY_FLAG CHAR(1), 
     CA_WEB_ONLY_FLAG CHAR(1), 
     BAB_WEB_ONLY_FLAG CHAR(1), 
     JDA_DEPT_ID NUMBER(3), 
     JDA_SUB_DEPT_ID NUMBER(3) , 
     TAX_CD VARCHAR2(30), 
     SWATCH_FLAG CHAR(1), 
     GIFT_CERT_FLAG CHAR(1), 
     SHOP_GUIDE_ID NUMBER(10), 
     SKU_COLLEGE_ID NUMBER(10), 
     SKU_TYPE_CD CHAR(2), 
     EMAIL_OUT_OF_STOCK_FLAG CHAR(1), 
     PROP65_LIGHTING CHAR(1), 
     PROP65_CRYSTAL CHAR(1), 
     PROP65_DINNERWARE CHAR(1), 
     PROP65_OTHER CHAR(1), 
     GIFT_WRAP_ELIGIBLE CHAR(1), 
     UPC VARCHAR2(50), 
     BRAND_ID NUMBER(6), 
     ELIGIBLE_SHIP_METHODS VARCHAR2(100), 
     FREE_SHIPPING_METHODS VARCHAR2(100), 
     CA_FREE_SHIPPING_METHODS VARCHAR2(100), 
     BAB_FREE_SHIPPING_METHODS VARCHAR2(100), 
     NON_SHIPPABLE_STATES VARCHAR2(100), 
     VDC_SKU_TYPE CHAR(1), 
     VDC_SKU_MESSAGE VARCHAR2(200), 
     CA_ECOM_FULFILMENT_FLAG CHAR(1), 
     OVERWEIGHT_FLAG CHAR(1), 
     OVERSIZE_FLAG CHAR(1), 
     BBB_FORCE_BELOW_LINE CHAR(1), 
     BAB_FORCE_BELOW_LINE CHAR(1), 
     CA_FORCE_BELOW_LINE CHAR(1),
     DISABLE_FOREVER_PDP_FLAG CHAR(1),
     BAB_DISABLE_FOREVER_PDP_FLAG CHAR(1),
     CA_DISABLE_FOREVER_PDP_FLAG CHAR(1),
     GS_DISABLE_FOREVER_PDP_FLAG CHAR(1)
    ) 
;

ALTER TABLE ECP_ITEMS_RARE 
    ADD CONSTRAINT ECP_SKU_PK PRIMARY KEY ( FEED_ID, SKU_ID ) ;

ALTER TABLE ECP_ITEMS_RARE 
    ADD CONSTRAINT ECP_ITEMS_RARE_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_SKU_PRICING 
    ( 
     FEED_ID NUMBER(10)  NOT NULL , 
     SKU_ID NUMBER(9)  NOT NULL , 
     WAS_PRICE NUMBER(10,2) , 
     CA_WAS_PRICE NUMBER(10,2) , 
     JDA_RETAIL_PRICE NUMBER(10,2) , 
     CA_JDA_RETAIL_PRICE NUMBER(10,2) 
    ) 
;

ALTER TABLE ECP_SKU_PRICING 
    ADD CONSTRAINT ECP_SKU_PRICING_PK PRIMARY KEY ( FEED_ID, SKU_ID ) ;

ALTER TABLE ECP_SKU_PRICING 
    ADD CONSTRAINT ECP_SKU_PRICING_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_PRODUCT_TABS 
    ( 
     FEED_ID NUMBER(10)  NOT NULL , 
     SKU_ID NUMBER(9)  NOT NULL , 
     TAB_ID VARCHAR2(10)  NOT NULL , 
     TAB_NAME VARCHAR2(50) , 
     TAB_CONTENT VARCHAR2(2000) , 
     SITE_FLAG VARCHAR2(5) , 
     TAB_SEQUENCE NUMBER(10) , 
     OPERATION_FLAG CHAR(1) 
    ) 
;

ALTER TABLE ECP_PRODUCT_TABS 
    ADD CONSTRAINT ECP_PRODUCT_TABS_PK PRIMARY KEY ( FEED_ID, SKU_ID, TAB_ID) ;

ALTER TABLE ECP_PRODUCT_TABS 
    ADD CONSTRAINT ECP_PRODUCT_TABS_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_PRODUCT_TYPE_ROLLUP( 
     FEED_ID NUMBER(10)  NOT NULL , 
     ROLLUP_TYPE_ID VARCHAR2(10) , 
     ROLLUP_ATTRIBUTE VARCHAR2(100) 
);

ALTER TABLE ECP_PRODUCT_TYPE_ROLLUP 
    ADD CONSTRAINT ECP_PROD_ROLLUP_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_ITEM_COLOR_PICTURES( 
     FEED_ID NUMBER(10)  NOT NULL, 
     SKU_ID NUMBER(9)  NOT NULL, 
     COLOR_CD VARCHAR2(50), 
     DISABLE_FLAG CHAR(1), 
     MED_LOC VARCHAR2(100), 
     SWATCH_LOC VARCHAR2(100), 
     ZOOM_LOC VARCHAR2(100) 
);

ALTER TABLE ECP_ITEM_COLOR_PICTURES 
    ADD CONSTRAINT ECP_ITM_CLR_PICS_PK PRIMARY KEY ( FEED_ID, SKU_ID, COLOR_CD ) ;

ALTER TABLE ECP_ITEM_COLOR_PICTURES 
    ADD CONSTRAINT ECP_ITM_CLR_PICS_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE CLASS( 
     JDA_DEPT_ID NUMBER(3)  NOT NULL , 
     JDA_SUB_DEPT_ID NUMBER(3)  NOT NULL , 
     JDA_CLASS NUMBER(5)  NOT NULL , 
     DESCRIP VARCHAR2(35) 
) ;

ALTER TABLE CLASS 
    ADD CONSTRAINT CLASS_PK PRIMARY KEY ( JDA_DEPT_ID, JDA_CLASS, JDA_SUB_DEPT_ID ) ;

CREATE TABLE DEPT ( 
     JDA_DEPT_ID NUMBER(3)  NOT NULL , 
     DESCRIP VARCHAR2 (35) 
) ;

ALTER TABLE DEPT 
    ADD CONSTRAINT DEPT_PK PRIMARY KEY ( JDA_DEPT_ID ) ;

CREATE TABLE SUB_DEPT( 
     JDA_DEPT_ID NUMBER(3)  NOT NULL , 
     JDA_SUB_DEPT_ID NUMBER(3)  NOT NULL , 
     DESCRIP VARCHAR2(50) 
);

ALTER TABLE SUB_DEPT 
    ADD CONSTRAINT SUB_DEPT_PK PRIMARY KEY ( JDA_DEPT_ID, JDA_SUB_DEPT_ID ) ;

CREATE TABLE ECP_NODES( 
     FEED_ID NUMBER(10)  NOT NULL , 
     NODE_ID NUMBER(10)  NOT NULL , 
     NODE_NAME VARCHAR2 (35) , 
     NODE_IMAGE VARCHAR2 (100) , 
     ROOT_NODE_FLAG CHAR (1) , 
     DISPLAY_FLAG CHAR (1) , 
     SEQUENCE_NUM NUMBER(10) , 
     SITE_FLAG CHAR (1 CHAR) , 
     NODE_TYPE VARCHAR2 (10) , 
     PHANTOM_CATEGORY VARCHAR2 (10) , 
     OPERATION_FLAG CHAR (1) , 
     IS_COLLEGE VARCHAR2 (20) , 
     SHOP_GUIDE_ID NUMBER(10)
);

ALTER TABLE ECP_NODES 
    ADD CONSTRAINT ECP_NODES_PK PRIMARY KEY ( FEED_ID, NODE_ID ) ;

ALTER TABLE ECP_NODES 
    ADD CONSTRAINT ECP_NODES_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_NODE_SKU( 
     FEED_ID NUMBER(10)  NOT NULL , 
     NODE_ID NUMBER(10)  NOT NULL , 
     SKU_ID NUMBER(9)  NOT NULL , 
     SEQUENCE_NUM NUMBER (20) , 
     SITE_FLAG VARCHAR2(5),
     OPERATION_FLAG CHAR (1) 
);

ALTER TABLE ECP_NODE_SKU 
    ADD CONSTRAINT ECP_NODE_SKU_PK PRIMARY KEY ( FEED_ID, NODE_ID, SKU_ID) ;

ALTER TABLE ECP_NODE_SKU 
    ADD CONSTRAINT ECP_NODE_SKU_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_NODE_PARENT( 
     FEED_ID NUMBER(10)  NOT NULL , 
     NODE_ID NUMBER(10)  NOT NULL , 
     CHILD_NODE_ID NUMBER (10)  NOT NULL , 
     SEQUENCE_NUM NUMBER (20) , 
     OPERATION_FLAG CHAR (1) 
);

ALTER TABLE ECP_NODE_PARENT 
    ADD CONSTRAINT ECP_NODE_PARENT_PK PRIMARY KEY ( FEED_ID, NODE_ID, CHILD_NODE_ID ) ;

ALTER TABLE ECP_NODE_PARENT 
    ADD CONSTRAINT ECP_NODE_PARENT_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_NODES_KEYWORDS( 
     FEED_ID NUMBER(10)  NOT NULL , 
     NODE_ID NUMBER(10)  NOT NULL , 
     KEYWORD_STRING VARCHAR2 (2000) 
);

ALTER TABLE ECP_NODES_KEYWORDS 
    ADD CONSTRAINT ECP_NODE_KEYWDS_PK PRIMARY KEY ( FEED_ID, NODE_ID ) ;

ALTER TABLE ECP_NODES_KEYWORDS 
    ADD CONSTRAINT ECP_NODES_KEYWORDS_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_PRODUCTS_KEYWORDS( 
     FEED_ID NUMBER(10)  NOT NULL , 
     SKU_ID NUMBER(9)  NOT NULL , 
     KEYWORD_STRING VARCHAR2 (1000) 
);

ALTER TABLE ECP_PRODUCTS_KEYWORDS 
    ADD CONSTRAINT ECP_PROD_KEYWS_FK_PK PRIMARY KEY ( FEED_ID, SKU_ID ) ;

ALTER TABLE ECP_PRODUCTS_KEYWORDS 
    ADD CONSTRAINT ECP_PROD_KEYWS_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_RELATED_ITEMS( 
     FEED_ID NUMBER(10)  NOT NULL , 
     SKU_ID NUMBER(9)  NOT NULL , 
     CHILD_SKU_ID NUMBER(9) , 
     RELATED_TYPE_CD CHAR(2) , 
     SEQUENCE_NUM NUMBER(10) , 
     LIKE_UNLIKE_FLAG CHAR(1), 
     OPERATION_FLAG CHAR(1) 
);

ALTER TABLE ECP_RELATED_ITEMS 
    ADD CONSTRAINT ECP_REL_ITEMS_PK PRIMARY KEY ( FEED_ID, SKU_ID, CHILD_SKU_ID ) ;

ALTER TABLE ECP_RELATED_ITEMS 
    ADD CONSTRAINT ECP_REL_ITEMS_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_BRANDS( 
     FEED_ID NUMBER(10)  NOT NULL , 
     BRAND_ID NUMBER(6)  NOT NULL , 
     BRAND_NAME VARCHAR2(100) , 
     BRAND_LOGO	VARCHAR2(100), 
     SITE_FLAG VARCHAR2 (5),
     DISPLAY_FLAG CHAR(1)
);

ALTER TABLE ECP_BRANDS 
    ADD CONSTRAINT ECP_BRANDS_PK PRIMARY KEY ( FEED_ID, BRAND_ID ) ;

ALTER TABLE ECP_BRANDS 
    ADD CONSTRAINT ECP_BRANDS_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_REBATES( 
     FEED_ID NUMBER(10)  NOT NULL , 
     REBATE_ID NUMBER(8)  NOT NULL , 
     DESCRIPTION VARCHAR2(400) , 
     START_DT DATE, 
     END_DT DATE, 
     REBATE_URL VARCHAR2(100), 
     SITE_FLAG VARCHAR2 (5) 
);

ALTER TABLE ECP_REBATES 
    ADD CONSTRAINT ECP_REBATES_PK PRIMARY KEY ( FEED_ID, REBATE_ID  ) ;

ALTER TABLE ECP_REBATES 
    ADD CONSTRAINT ECP_REBATES_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_SKU_REBATES( 
     FEED_ID NUMBER(10)  NOT NULL , 
     SKU_ID  NUMBER(9) NOT NULL,
     REBATE_ID NUMBER(8)  NOT NULL,
     OPERATION_FLAG CHAR(1)
);

ALTER TABLE ECP_SKU_REBATES 
    ADD CONSTRAINT ECP_SKU_REBATES_PK PRIMARY KEY ( FEED_ID, SKU_ID, REBATE_ID ) ;

ALTER TABLE ECP_SKU_REBATES 
    ADD CONSTRAINT ECP_SKU_REBATS_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);


CREATE TABLE ECP_PROD_MEDIA(
    FEED_ID NUMBER(10)  NOT NULL ,
    MEDIA_ID NUMBER(10) NOT NULL,
    SKU_ID NUMBER(10) NOT NULL,
    SEQUENCE NUMBER(10) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    COMMENTS VARCHAR2(200),
    SITE_FLAG VARCHAR2(5),
    WIDGET_ID VARCHAR2(10),
    OPERATION_FLAG CHAR(1) 
);

ALTER TABLE ECP_PROD_MEDIA 
    ADD CONSTRAINT ECP_PROD_MEDIA_PK PRIMARY KEY ( FEED_ID, MEDIA_ID, SKU_ID, SEQUENCE ) ;

ALTER TABLE ECP_PROD_MEDIA 
    ADD CONSTRAINT ECP_PROD_MEDIA_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_MEDIA(
    FEED_ID NUMBER(10)  NOT NULL ,
    MEDIA_ID NUMBER(10) NOT NULL,
    MEDIA_TYPE VARCHAR2(30),
    PROVIDER_ID NUMBER(5),
    MEDIA_SOURCE VARCHAR2(500),
    MEDIA_DESCRIP VARCHAR2(500),
    COMMENTS VARCHAR2(500),
    MEDIA_TRANSCIPT VARCHAR2(4000)
);

ALTER TABLE ECP_MEDIA 
    ADD CONSTRAINT ECP_MEDIA_PK PRIMARY KEY ( FEED_ID, MEDIA_ID ) ;

ALTER TABLE ECP_MEDIA 
    ADD CONSTRAINT ECP_MEDIA_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE ECP_SKU_THRESHOLDS(
    FEED_ID NUMBER(10)  NOT NULL ,
    JDA_DEPT_ID NUMBER(3), 
    JDA_SUB_DEPT_ID NUMBER(3),
    JDA_CLASS NUMBER(5),
    SKU_ID NUMBER(9) NOT NULL,
    SITE_FLAG VARCHAR2(5),
    TYPE VARCHAR2(50),
    THRESHOLD_LIMITED NUMBER(10),
    THRESHOLD_AVAILABLE NUMBER(10)
);

ALTER TABLE ECP_SKU_THRESHOLDS 
    ADD CONSTRAINT ECP_SKU_THSHOLDS_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE STATES( 
     STATE_CD CHAR(3)  NOT NULL , 
     DESCRIP VARCHAR2(200) , 
     NEXUS_FLAG CHAR(1) , 
     NEXUS_BABY_FLAG CHAR(1) , 
     NEXUS_CA_FLAG CHAR(1) ,
     SITE_FLAG VARCHAR2(5),
     COUNTRY_CD VARCHAR2(10) , 
     BOPUS_FLAG CHAR(1)
);

ALTER TABLE STATES 
    ADD CONSTRAINT STATES_PK PRIMARY KEY (STATE_CD) ;

ALTER TABLE ECP_ITEM_ATTRIBUTES(
    ITEM_ATTRIBUTE_ID NUMBER(10) NOT NULL,
    ITEM_VALUE_ID NUMBER(10),
    DESCRIP VARCHAR2(50),
    START_DT DATE,
    END_DT DATE,
    SITE_FLAG VARCHAR2(5),
    IMAGE_URL VARCHAR2(100),
    ACTION_URL VARCHAR2(150),
    PLACE_HOLDER VARCHAR2(10),
    PRIORITY NUMBER(10)
);

ALTER TABLE ECP_ITEM_ATTRIBUTES 
    ADD CONSTRAINT ECP_ITEM_ATTRIBS_PK PRIMARY KEY (ITEM_ATTRIBUTE_ID, ITEM_VALUE_ID) ;

CREATE TABLE ECP_SKU_ATTRIBUTES(
    FEED_ID NUMBER(10) NOT NULL,
    SKU_ID NUMBER(9) NOT NULL,
    ITEM_ATTRIBUTE_ID NUMBER(10) NOT NULL,
    ITEM_VALUE_ID NUMBER(10),
    SITE_FLAG VARCHAR2(5),
    MISC_INFO VARCHAR2(255),
    START_DT DATE,
    END_DT DATE,
    OPERATION_FLAG CHAR(1)
);

ALTER TABLE ECP_SKU_ATTRIBUTES 
    ADD CONSTRAINT ECP_SKU_ATTRIBS_PK PRIMARY KEY (FEED_ID, SKU_ID, ITEM_ATTRIBUTE_ID,ITEM_VALUE_ID) ;

ALTER TABLE ECP_SKU_ATTRIBUTES 
    ADD CONSTRAINT ECP_SKU_ATTRIBS_FK FOREIGN KEY(FEED_ID) 
    REFERENCES ECP_FEED_MONITORING(FEED_ID);

CREATE TABLE SCHOOLS( 
     SCHOOLD_ID NUMBER(10)  NOT NULL , 
     SCHOOL_NAME VARCHAR2(250) , 
     SMALL_LOG0_URL VARCHAR2(100) , 
     LARGE_LOG0_URL VARCHAR2(100) , 
     SMALL_WELCOME_MSG VARCHAR2(100),
     LARGE_WELCOME_MSG VARCHAR2(500),
     PROMOTION_ID VARCHAR2(50),
     CITY VARCHAR2(50) , 
     STATE_CD CHAR(3) , 
     ADDR1 VARCHAR2(100) , 
     ADDR2 VARCHAR2(100) , 
     ZIP VARCHAR2 (9),
     PREF_STORE_ID VARCHAR2(50),
     PDF_URL VARCHAR2(100),
     COLLEGE_TAG VARCHAR2(100),
     LAST_MODIFIED_DATE DATE,
     IMAGE_URL VARCHAR2(100)
);

ALTER TABLE SCHOOLS 
    ADD CONSTRAINT SCHOOLS_PK PRIMARY KEY ( SCHOOLD_ID ) ;