-- drop table BBB_SCHOOLS;

CREATE TABLE BBB_SCHOOLS (
	school_id 		VARCHAR2(40)	NOT NULL,
	SCHOOL_NAME 		VARCHAR2(254)	NULL,
	SMALL_LOGO_URL 		VARCHAR2(254)	NULL,
	LARGE_LOGO_URL 		VARCHAR2(254)	NULL,
	SMALL_WELCOME_MSG 	VARCHAR2(254)	NULL,
	LARGE_WELCOME_MSG 	VARCHAR2(1000)	NULL,
	PROMOTION_ID 		VARCHAR2(254)	NULL,
	ADDR_LINE1 		VARCHAR2(254)	NULL,
	ADDR_LINE2 		VARCHAR2(254)	NULL,
	CITY 			VARCHAR2(254)	NULL,
	STATE 			VARCHAR2(40)	NULL REFERENCES BBB_STATES(STATE_ID),
	ZIP 			VARCHAR2(40)	NULL,
	CREATE_DATE 		DATE	NULL,
	LAST_MODIFIED_DATE 	DATE	NULL,
	IMAGE_URL 		VARCHAR2(254)	NULL,
	PREF_STORE_ID 		VARCHAR2(40)	NULL,
	PDF_URL 		VARCHAR2(254)	NULL,
	COLLEGE_TAG 		VARCHAR2(254)	NULL,
	COLLEGE_LOGO 		VARCHAR2(254)	NULL,
	asset_version		INT NOT NULL,
	workspace_id		VARCHAR(40) NOT NULL,
	branch_id		VARCHAR(40) NOT NULL,
	is_head			NUMERIC(1) NOT NULL,
	version_deleted		NUMERIC(1) NOT NULL,
	version_editable	NUMERIC(1) NOT NULL,
	pred_version		INT NULL,
	checkin_date		TIMESTAMP NULL,
	PRIMARY KEY(school_id, asset_version)
);

