//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.12-1.0.0.0_2-1-12-ea 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 01:33:00 PM IST 
//


package com.bbb.commerce.browse.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DATARECORD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DATARECORD">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SKU_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PRODUCT_ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PRODUCT_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EMAIL_ADDR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CUST_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="USER_IP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="REQUESTED_DT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="IN_STOCK_NOTIFY_DT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="NOTICE_1_DT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="NOTICE_2_DT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="UNSUBSCRIBE_DT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="FINAL_NOTICE_DT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="SITE_FLAG" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DATARECORD", propOrder = {
    "skuid",
    "productid",
    "productname",
    "emailaddr",
    "custname",
    "userip",
    "requesteddt",
    "instocknotifydt",
    "notice1DT",
    "notice2DT",
    "unsubscribedt",
    "finalnoticedt",
    "siteflag"
})
public class DATARECORD {

    @XmlElement(name = "SKU_ID")
    protected String skuid;
    @XmlElement(name = "PRODUCT_ID")
    protected String productid;
    @XmlElement(name = "PRODUCT_NAME")
    protected String productname;
    @XmlElement(name = "EMAIL_ADDR")
    protected String emailaddr;
    @XmlElement(name = "CUST_NAME")
    protected String custname;
    @XmlElement(name = "USER_IP")
    protected String userip;
    @XmlElement(name = "REQUESTED_DT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar requesteddt;
    @XmlElement(name = "IN_STOCK_NOTIFY_DT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar instocknotifydt;
    @XmlElement(name = "NOTICE_1_DT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar notice1DT;
    @XmlElement(name = "NOTICE_2_DT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar notice2DT;
    @XmlElement(name = "UNSUBSCRIBE_DT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar unsubscribedt;
    @XmlElement(name = "FINAL_NOTICE_DT")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar finalnoticedt;
    @XmlElement(name = "SITE_FLAG")
    protected String siteflag;

    /**
     * Gets the value of the skuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKUID() {
        return skuid;
    }

    /**
     * Sets the value of the skuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKUID(String value) {
        this.skuid = value;
    }

    /**
     * Gets the value of the productid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTID() {
        return productid;
    }

    /**
     * Sets the value of the productid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTID(String value) {
        this.productid = value;
    }

    /**
     * Gets the value of the productname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTNAME() {
        return productname;
    }

    /**
     * Sets the value of the productname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTNAME(String value) {
        this.productname = value;
    }

    /**
     * Gets the value of the emailaddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAILADDR() {
        return emailaddr;
    }

    /**
     * Sets the value of the emailaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAILADDR(String value) {
        this.emailaddr = value;
    }

    /**
     * Gets the value of the custname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTNAME() {
        return custname;
    }

    /**
     * Sets the value of the custname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTNAME(String value) {
        this.custname = value;
    }

    /**
     * Gets the value of the userip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERIP() {
        return userip;
    }

    /**
     * Sets the value of the userip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERIP(String value) {
        this.userip = value;
    }

    /**
     * Gets the value of the requesteddt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getREQUESTEDDT() {
        return requesteddt;
    }

    /**
     * Sets the value of the requesteddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setREQUESTEDDT(XMLGregorianCalendar value) {
        this.requesteddt = value;
    }

    /**
     * Gets the value of the instocknotifydt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getINSTOCKNOTIFYDT() {
        return instocknotifydt;
    }

    /**
     * Sets the value of the instocknotifydt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setINSTOCKNOTIFYDT(XMLGregorianCalendar value) {
        this.instocknotifydt = value;
    }

    /**
     * Gets the value of the notice1DT property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNOTICE1DT() {
        return notice1DT;
    }

    /**
     * Sets the value of the notice1DT property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNOTICE1DT(XMLGregorianCalendar value) {
        this.notice1DT = value;
    }

    /**
     * Gets the value of the notice2DT property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNOTICE2DT() {
        return notice2DT;
    }

    /**
     * Sets the value of the notice2DT property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNOTICE2DT(XMLGregorianCalendar value) {
        this.notice2DT = value;
    }

    /**
     * Gets the value of the unsubscribedt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUNSUBSCRIBEDT() {
        return unsubscribedt;
    }

    /**
     * Sets the value of the unsubscribedt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUNSUBSCRIBEDT(XMLGregorianCalendar value) {
        this.unsubscribedt = value;
    }

    /**
     * Gets the value of the finalnoticedt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFINALNOTICEDT() {
        return finalnoticedt;
    }

    /**
     * Sets the value of the finalnoticedt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFINALNOTICEDT(XMLGregorianCalendar value) {
        this.finalnoticedt = value;
    }

    /**
     * Gets the value of the siteflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSITEFLAG() {
        return siteflag;
    }

    /**
     * Sets the value of the siteflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSITEFLAG(String value) {
        this.siteflag = value;
    }

}
