CREATE TABLE BBB_SEO_SITE_TRANSLATE(    
	SEO_TAG_ID	VARCHAR2(40) NOT NULL,
	TRANSLATION_ID	VARCHAR2(40) NOT NULL,
	PRIMARY KEY(SEO_TAG_ID, TRANSLATION_ID)
);

CREATE TABLE BBB_SEO_TRANSLATION(
	TRANSLATION_ID	 VARCHAR2(40) NOT NULL,
	SITE_ID			 VARCHAR2(40) NOT NULL,
	LOCALE_ID		 VARCHAR2(40) NOT NULL,
	TITLE            VARCHAR2(254),
	DESCRIPTION      VARCHAR2(254), 
	KEYWORDS         VARCHAR2(254), 
	CONTENT_KEY      VARCHAR2(100),
	PRIMARY KEY(TRANSLATION_ID)
);
