CREATE TABLE BBB_SEO_SITE_TRANSLATE(
    ASSET_VERSION    NUMBER(38) NOT NULL,
	SEO_TAG_ID	VARCHAR2(40),
	TRANSLATION_ID	VARCHAR2(40),
	PRIMARY KEY(ASSET_VERSION,SEO_TAG_ID,TRANSLATION_ID)
);

CREATE TABLE BBB_SEO_TRANSLATION(
	ASSET_VERSION    NUMBER(38) NOT NULL,
	WORKSPACE_ID     VARCHAR2(40) NOT NULL,  
	BRANCH_ID        VARCHAR2(40) NOT NULL,  
	IS_HEAD          NUMBER(1) NOT NULL,      
	VERSION_DELETED  NUMBER(1) NOT NULL,      
	VERSION_EDITABLE NUMBER(1) NOT NULL,      
	PRED_VERSION     NUMBER(38),     
	CHECKIN_DATE     TIMESTAMP(6),
	TRANSLATION_ID	 VARCHAR2(40) NOT NULL,
	SITE_ID			 VARCHAR2(40) NOT NULL,
	LOCALE_ID		 VARCHAR2(40) NOT NULL,
	TITLE            VARCHAR2(254),
	DESCRIPTION      VARCHAR2(254), 
	KEYWORDS         VARCHAR2(254), 
	CONTENT_KEY      VARCHAR2(100),
	CHECK (version_deleted IN (0, 1)),
	CHECK (version_editable IN (0, 1)),
	CHECK (is_head IN (0, 1)),
	PRIMARY KEY(TRANSLATION_ID,ASSET_VERSION)
);
