package com.bbb.internationalshipping.fulfillment.scheduler;

import com.bbb.internationalshipping.fulfillment.processor.InternationalPurchaseOrderProcessor;
import com.bbb.internationalshipping.utils.InternationalShipTools;

import atg.service.scheduler.ScheduledJob;
import atg.service.scheduler.Scheduler;
import atg.service.scheduler.SingletonSchedulableService;



/**
 * The Class POProcessScheduler.The Scheduler fulfills the ATG order through PO files
 * generated by Borderfree
 * 
 */
public class POProcessScheduler extends SingletonSchedulableService {
	/** The international purchase order processor. */
	private InternationalPurchaseOrderProcessor internationalPurchaseOrderProcessor;


	/** Disable current scheduler from executing its task. */
	private boolean disableService;
	private InternationalShipTools tools;


	public InternationalShipTools getTools() {
		return tools;
	}

	public void setTools(InternationalShipTools tools) {
		this.tools = tools;
	}

	/**
	 * Disable current scheduler from executing its task.
	 * 
	 * @return boolean value for enable/disable for scheduler.
	 */
	public boolean isDisableService() {
		return disableService;
	}

	/**
	 * Disable current scheduler from executing its task.
	 * 
	 * @param pDisableService
	 *            Value for disableService will be set by properties file.
	 */
	public void setDisableService(final boolean pDisableService) {
		this.disableService = pDisableService;
	}

	/**
	 * Gets the international purchase order processor.
	 *
	 * @return the international purchase order processor
	 */
	public InternationalPurchaseOrderProcessor getInternationalPurchaseOrderProcessor() {
		return internationalPurchaseOrderProcessor;
	}

	/**
	 * Sets the international purchase order processor.
	 *
	 * @param internationalPurchaseOrderProcessor 
	 * the new international purchase order processor
	 */
	public void setInternationalPurchaseOrderProcessor(
			final InternationalPurchaseOrderProcessor internationalPurchaseOrderProcessor) {
		this.internationalPurchaseOrderProcessor = internationalPurchaseOrderProcessor;
	}

	/**
	 * This method will be called internally when the Scheduler component
	 * is invoked, based on a scheduler.
	 *
	 * @param scheduler the scheduler
	 * @param scheduledjob the scheduled job
	 */
	public void doScheduledTask(final Scheduler scheduler, final ScheduledJob scheduledjob) {
		 this.logInfo(":: Entering doScheduledTask ");

		if (!isDisableService() && this.tools.checkIntSwitch()) {
			internationalPurchaseOrderProcessor.processPOFiles();
		}else{
			 this.logInfo("POProcessScheduler did not start because it's not enabled");
		}
		this.logDebug(":: Exiting doScheduledTask ");
	}	


	/**
	 * Helps to trigger schedule task manually
	 */
	public void executeDoScheduledTask() {

		this.logDebug("Entry executeDoScheduledTask");

		doScheduledTask(null,
				new ScheduledJob("BBBIntlShipPOProcessScheduler", "POProcessScheduler to submit International Order Purchase orders to ATG", "", null, null, false));

		this.logDebug("Exit executeDoScheduledTask");

	}

	public void logDebug(final String pMessage) {
        if (this.isLoggingDebug()) {
            this.logDebug(pMessage, null);
        }
    }
	
	public void logInfo(final String pMessage) {
        if (this.isLoggingInfo()) {
            this.logInfo(pMessage, null);
        }
    }
}
