--============  LIST TYPE  ===============
DROP TABLE BBB_MISC.BBB_LIST_TYPE;

CREATE TABLE BBB_MISC.BBB_LIST_TYPE
(
	TYPE_ID				VARCHAR2(40) NOT NULL,
	TYPE_NAME			VARCHAR2(100) NOT NULL,
	SUB_TYPE_CODE VARCHAR2(10) NULL,
	SUB_TYPE_NAME VARCHAR2(100) NULL,
	CREATE_USER VARCHAR2(40) NOT NULL,
	CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
	LAST_MOD_USER VARCHAR2(40) NOT NULL,
	LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
	CONSTRAINT BBB_LIST_TYPE_PK PRIMARY KEY(TYPE_ID)
);

CREATE UNIQUE INDEX BBB_LIST_TYPE_SUB_TYPE_UK ON BBB_MISC.BBB_LIST_TYPE(SUB_TYPE_CODE);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_TYPE TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_TYPE TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_TYPE TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_TYPE TO BBB_SWITCH_B;

--============  LIST ===============
DROP TABLE BBB_MISC.BBB_LIST;

CREATE TABLE BBB_MISC.BBB_LIST
(
	LIST_ID				VARCHAR2(40) NOT NULL,
	SUB_TYPE_CODE VARCHAR2(10) NOT NULL,
	DISPLAY_NAME		VARCHAR2(254) NOT NULL,
	SEQUENCE_NUM		NUMBER NOT NULL,  
	IS_DISABLED			NUMBER(1) NOT NULL,
  ALLOW_DUPLICATES NUMBER(1) NOT NULL,
  SITE_FLAG VARCHAR2(10) NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_LIST_PK PRIMARY KEY(LIST_ID)
);

ALTER TABLE "BBB_MISC"."BBB_LIST" ADD CHECK (IS_DISABLED IN (0, 1)) ENABLE;
ALTER TABLE "BBB_MISC"."BBB_LIST" ADD CHECK (ALLOW_DUPLICATES IN (0, 1)) ENABLE;

CREATE UNIQUE INDEX BBB_LIST_SUB_TYPE_UK ON BBB_MISC.BBB_LIST(SUB_TYPE_CODE);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST TO BBB_SWITCH_B;

--============  LIST TO PARENT CATEGORY MAPPING ===============
DROP TABLE BBB_MISC.BBB_LIST_CHLDCAT;

CREATE TABLE BBB_MISC.BBB_LIST_CHLDCAT
(
	LIST_ID				VARCHAR2(40) NOT NULL,
	LIST_CAT_ID		VARCHAR2(40) NOT NULL,
	SEQUENCE_NUM	NUMBER NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_LIST_CHLDCAT_PK PRIMARY KEY (LIST_ID, LIST_CAT_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_CHLDCAT TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_CHLDCAT TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CHLDCAT TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_CHLDCAT TO BBB_SWITCH_B;

--============  CATEGORY  ===============
DROP TABLE BBB_MISC.BBB_LIST_CATEGORY;

CREATE TABLE BBB_MISC.BBB_LIST_CATEGORY
(
	LIST_CAT_ID				VARCHAR2(40) NOT NULL,
	NAME					    VARCHAR2(254) NOT NULL,
	CATEGORY_URL			VARCHAR2(254),
	IMAGE_URL				  VARCHAR2(254),
	SUGGESTED_QTY			NUMBER,
	PRIMARY_PARENT_CAT_ID	VARCHAR2(40),
	DISPLAY_NAME			VARCHAR2(500) NOT NULL,
	THRESHOLD_QTY			NUMBER,
	THRESHOLD_AMT			NUMBER(19, 7),
	SERVICE_TYPE_CD		VARCHAR2(10),
	IS_DISABLED				NUMBER(1) NOT NULL,
	IS_CONFIG_COMPLETE			NUMBER(1) NOT NULL,
	IS_VISIBLE_ON_CHECKLIST NUMBER(1) NOT NULL,
	IS_VISIBLE_ON_REG_LIST NUMBER(1) NOT NULL,
	IS_CHILD_PRD_NEEDED_TO_DISP NUMBER(1) NOT NULL,
	BABY_CATEGORY_URL VARCHAR2(254),
	BABY_IMAGE_URL    VARCHAR2(254),
	CA_CATEGORY_URL   VARCHAR2(254),
	CA_IMAGE_URL      VARCHAR2(254),
	TBS_CATEGORY_URL  VARCHAR2(254),
	TBS_IMAGE_URL     VARCHAR2(254),
	CREATE_USER       VARCHAR2(40) NOT NULL,
	CREATE_DATE       TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
	LAST_MOD_USER     VARCHAR2(40) NOT NULL,
	LAST_MOD_DATE     TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
	CONSTRAINT BBB_LIST_CATEGORY_PK PRIMARY KEY (LIST_CAT_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_CATEGORY TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_CATEGORY TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CATEGORY TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_CATEGORY TO BBB_SWITCH_B;

--============  CATEGORY HIERARCHY ===============
DROP TABLE BBB_MISC.BBB_LIST_CAT_CHLDCAT;

CREATE TABLE BBB_MISC.BBB_LIST_CAT_CHLDCAT
(
	LIST_CAT_ID		VARCHAR2(40) NOT NULL,
	CHILD_LIST_CAT_ID	VARCHAR2(40) NOT NULL,
	SEQUENCE_NUM	NUMBER NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_LIST_CAT_CHLDCAT_PK PRIMARY KEY (LIST_CAT_ID, CHILD_LIST_CAT_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_CHLDCAT TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_CHLDCAT TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_CHLDCAT TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_CHLDCAT TO BBB_SWITCH_B;

--============  LOOKUP TABLES  ===============
DROP TABLE BBB_MISC.BBB_LIST_JDA_FACETS;

CREATE TABLE BBB_MISC.BBB_LIST_JDA_FACETS
(
  JDA_DEPT_ID				VARCHAR2(40)  NOT NULL,
  JDA_SUB_DEPT_ID VARCHAR2(40) NULL,
  JDA_CLASS VARCHAR2(40) NULL,
  FACET_ID VARCHAR2(40) NOT NULL,
  FACET_VALUE_ID VARCHAR2(40) NULL,
  FACET_VALUE_DESC VARCHAR2(2000) NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL
);

CREATE UNIQUE INDEX BBB_LIST_JDA_FACETS_UK ON BBB_MISC.BBB_LIST_JDA_FACETS(JDA_DEPT_ID, JDA_SUB_DEPT_ID, JDA_CLASS, FACET_ID, FACET_VALUE_ID);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_JDA_FACETS TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_JDA_FACETS TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_JDA_FACETS TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_JDA_FACETS TO BBB_SWITCH_B;


DROP TABLE BBB_MISC.BBB_LIST_EPH_FACETS;

CREATE TABLE BBB_MISC.BBB_LIST_EPH_FACETS
(
	EPH_ID	 VARCHAR2(40) NOT NULL,
  FACET_ID VARCHAR2(40) NOT NULL,
  FACET_VALUE_ID VARCHAR2(40) NULL,
  FACET_VALUE_DESC VARCHAR2(2000) NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL
);

CREATE UNIQUE INDEX BBB_LIST_EPH_FACETS_UK ON BBB_MISC.BBB_LIST_EPH_FACETS(EPH_ID, FACET_ID, FACET_VALUE_ID);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_EPH_FACETS TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_EPH_FACETS TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_EPH_FACETS TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_EPH_FACETS TO BBB_SWITCH_B;

DROP TABLE BBB_MISC.BBB_FACET_VALUE_PAIRS;

CREATE TABLE BBB_MISC.BBB_FACET_VALUE_PAIRS
(
	FACET_ID VARCHAR2(40) NOT NULL,
  FACET_VALUE_ID VARCHAR2(40) NULL,
  FACET_VALUE_DESC VARCHAR2(2000) NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL
);

CREATE UNIQUE INDEX BBB_FACET_VALUE_PAIRS_UK ON BBB_MISC.BBB_FACET_VALUE_PAIRS(FACET_ID, FACET_VALUE_ID);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_FACET_VALUE_PAIRS TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_FACET_VALUE_PAIRS TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_FACET_VALUE_PAIRS TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_FACET_VALUE_PAIRS TO BBB_SWITCH_B;

--============  JDA BASED RULES  ===============
DROP TABLE BBB_MISC.BBB_LIST_CAT_JDA;

CREATE TABLE BBB_MISC.BBB_LIST_CAT_JDA
(
	RULE_ID	VARCHAR2(40) NOT NULL,
	LIST_CAT_ID  VARCHAR2(40) NOT NULL,
	JDA_DEPT_ID	 VARCHAR2(40) NOT NULL,
	JDA_SUB_DEPT_ID VARCHAR2(40) NOT NULL,
	JDA_CLASS VARCHAR2(40) NULL,
	SEQUENCE_NUM	NUMBER NOT NULL,
	FACET_RULE_ID  VARCHAR2(40) NULL,
	CREATE_USER VARCHAR2(40) NOT NULL,
	CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
	LAST_MOD_USER VARCHAR2(40) NOT NULL,
	LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
	CONSTRAINT BBB_LIST_CAT_JDA_PK PRIMARY KEY (RULE_ID)  
);

CREATE UNIQUE INDEX BBB_LIST_CAT_JDA_UK ON BBB_MISC.BBB_LIST_CAT_JDA(LIST_CAT_ID, JDA_DEPT_ID, JDA_SUB_DEPT_ID, JDA_CLASS, SEQUENCE_NUM);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_JDA TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_JDA TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_JDA TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_JDA TO BBB_SWITCH_B;

--============  EPH BASED RULES  ===============
DROP TABLE BBB_MISC.BBB_LIST_CAT_EPH;

CREATE TABLE BBB_MISC.BBB_LIST_CAT_EPH
(
	RULE_ID  VARCHAR2(40) NOT NULL,
	LIST_CAT_ID  VARCHAR2(40) NOT NULL,
	EPH_NODE_ID	 VARCHAR2(40) NOT NULL,
	SEQUENCE_NUM	NUMBER NOT NULL,
	FACET_RULE_ID  VARCHAR2(40) NULL,
	CREATE_USER VARCHAR2(40) NOT NULL,
	CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
	LAST_MOD_USER VARCHAR2(40) NOT NULL,
	LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
	CONSTRAINT BBB_LIST_CAT_EPH_PK PRIMARY KEY (RULE_ID)
);

CREATE UNIQUE INDEX BBB_LIST_CAT_EPH_UK ON BBB_MISC.BBB_LIST_CAT_EPH(LIST_CAT_ID,EPH_ID,SEQUENCE_NUM);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_EPH TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_EPH TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_EPH TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_EPH TO BBB_SWITCH_B;

--=============  FACETS BASED RULES  ===============--
DROP TABLE BBB_MISC.BBB_LIST_CAT_FACET;

CREATE TABLE BBB_MISC.BBB_LIST_CAT_FACET
(
	RULE_ID VARCHAR2(40) NOT NULL,
	LIST_CAT_ID  VARCHAR2(40) NOT NULL,
  SEQUENCE_NUM	NUMBER NOT NULL,
	FACET_RULE_ID  VARCHAR2(40) NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_LIST_CAT_FACET_PK PRIMARY KEY (RULE_ID)
);

CREATE UNIQUE INDEX BBB_LIST_CAT_FACET_UK ON BBB_MISC.BBB_LIST_CAT_FACET(LIST_CAT_ID,SEQUENCE_NUM);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_FACET TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_FACET TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_FACET TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_FACET TO BBB_SWITCH_B;

--===============  Manually curated list for category to SKU mapping  =============--
DROP TABLE BBB_MISC.BBB_LIST_CAT_SKU;

CREATE TABLE BBB_MISC.BBB_LIST_CAT_SKU
(
	RULE_ID VARCHAR2(40) NOT NULL,
	LIST_CAT_ID  VARCHAR2(40) NOT NULL,
  SKU_ID  VARCHAR2(40) NOT NULL,
  RULE_EVALUATION_CD VARCHAR2(10) NOT NULL,
  SEQUENCE_NUM	NUMBER NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_LIST_CAT_SKU_PK PRIMARY KEY(RULE_ID)
);

CREATE UNIQUE INDEX BBB_LIST_CAT_SKU_UK ON BBB_MISC.BBB_LIST_CAT_SKU(LIST_CAT_ID,SKU_ID);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_SKU TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_SKU TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_SKU TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_SKU TO BBB_SWITCH_B;

--============  SAVED FACETS RULES  ==============
DROP TABLE BBB_MISC.BBB_FACET_RULES;

CREATE TABLE BBB_MISC.BBB_FACET_RULES
(
	RULE_ID  VARCHAR2(40) NOT NULL,
  FACET_RULE_NAME  VARCHAR2(254) NOT NULL,
	FACET_VALUE_PAIR_LIST  VARCHAR2(300) NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_FACET_RULES_PK PRIMARY KEY(RULE_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_FACET_RULES TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_FACET_RULES TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_FACET_RULES TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_FACET_RULES TO BBB_SWITCH_B;

--============  PACKAGE COUNTS  ============--
DROP TABLE BBB_MISC.BBB_LIST_PKG_CNT_FACETS;

CREATE TABLE BBB_MISC.BBB_LIST_PKG_CNT_FACETS
(
	FACET_ID  VARCHAR2(40) NOT NULL,
  FACET_VALUE_ID VARCHAR2(300) NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_LIST_PKG_CNT_FACETS_PK PRIMARY KEY(FACET_ID, FACET_VALUE_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_PKG_CNT_FACETS TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_LIST_PKG_CNT_FACETS TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_PKG_CNT_FACETS TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_LIST_PKG_CNT_FACETS TO BBB_SWITCH_B;

--===========  USER Table used by ATG front End  =============--
/*
CREATE TABLE BBB_MISC.BBB_USER_LIST
(
	USER_LIST_ID  VARCHAR2(40) NOT NULL,
  USER_ID VARCHAR2(300) NOT NULL,
  LIST_ID VARCHAR2(300) NOT NULL,
  DISPLAY_NAME VARCHAR2(254) NOT NULL,
  SEQUENCE_NUM NUMBER NOT NULL,
  USER_COMPLETED_CAT_LIST VARCHAR2(1000) NULL,
  IS_PUBLIC NUMBER(1,0) NOT NULL,
  EVENT_DATE NUMBER(9,0) NOT NULL,  
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_USER_LIST_PK PRIMARY KEY(USER_LIST_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_USER_LIST TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_USER_LIST TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_USER_LIST TO BBB_SWITCH_B;
*/
--=========== Backend, batch process output table used by ATG front end ===========--
DROP TABLE BBB_MISC.BBB_SKU_COMPUTED_ATTRIBUTES;

CREATE TABLE BBB_MISC.BBB_SKU_COMPUTED_ATTRIBUTES
(
  SKU_ID  VARCHAR2(40) NOT NULL,
  PACKAGE_CNT NUMBER NOT NULL,
  LIST_CATEGORIES VARCHAR2(4000) NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_SKU_COMPUTED_ATTRIBUTES_PK PRIMARY KEY(SKU_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_SKU_COMPUTED_ATTRIBUTES TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_SKU_COMPUTED_ATTRIBUTES TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_SKU_COMPUTED_ATTRIBUTES TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_SKU_COMPUTED_ATTRIBUTES TO BBB_SWITCH_B;


--=========== Backend, batch process output table used populated from CORE_PRV version of the stored procedure ===========--
DROP TABLE BBB_CORE_PRV.BBB_SKU_COMPUTED_ATTRIBUTES;

CREATE TABLE BBB_CORE_PRV.BBB_SKU_COMPUTED_ATTRIBUTES
(
  SKU_ID  VARCHAR2(40) NOT NULL,
  PACKAGE_CNT NUMBER NOT NULL,
  LIST_CATEGORIES VARCHAR2(4000) NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_SKU_COMPUTED_ATTRIBUTES_PK PRIMARY KEY(SKU_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_CORE_PRV.BBB_SKU_COMPUTED_ATTRIBUTES TO BBB_RO;
GRANT SELECT ON BBB_CORE_PRV.BBB_SKU_COMPUTED_ATTRIBUTES TO ECOMWEB;
GRANT SELECT ON BBB_CORE_PRV.BBB_SKU_COMPUTED_ATTRIBUTES TO BBB_SWITCH_A;
GRANT SELECT ON BBB_CORE_PRV.BBB_SKU_COMPUTED_ATTRIBUTES TO BBB_SWITCH_B;

--=========== Backend, batch process output table rolled up to Product level ===========--

DROP TABLE BBB_MISC.BBB_PROD_COMPUTED_ATTRIBUTES;

CREATE TABLE BBB_MISC.BBB_PROD_COMPUTED_ATTRIBUTES
(
  PRODUCT_ID  VARCHAR2(40) NOT NULL,
  LIST_CATEGORIES VARCHAR2(4000) NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_PR_COMPUTED_ATTRIBUTES_PK PRIMARY KEY(PRODUCT_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_PROD_COMPUTED_ATTRIBUTES TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_PROD_COMPUTED_ATTRIBUTES TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_PROD_COMPUTED_ATTRIBUTES TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_PROD_COMPUTED_ATTRIBUTES TO BBB_SWITCH_B;

--=========== Backend, batch process output table rolled up to Product level - populated from CORE_PRV process ===========--

DROP TABLE BBB_CORE_PRV.BBB_PROD_COMPUTED_ATTRIBUTES;

CREATE TABLE BBB_CORE_PRV.BBB_PROD_COMPUTED_ATTRIBUTES
(
  PRODUCT_ID  VARCHAR2(40) NOT NULL,
  LIST_CATEGORIES VARCHAR2(4000) NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_PR_COMPUTED_ATTRIBUTES_PK PRIMARY KEY(PRODUCT_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_CORE_PRV.BBB_PROD_COMPUTED_ATTRIBUTES TO BBB_RO;
GRANT SELECT ON BBB_CORE_PRV.BBB_PROD_COMPUTED_ATTRIBUTES TO ECOMWEB;
GRANT SELECT ON BBB_CORE_PRV.BBB_PROD_COMPUTED_ATTRIBUTES TO BBB_SWITCH_A;
GRANT SELECT ON BBB_CORE_PRV.BBB_PROD_COMPUTED_ATTRIBUTES TO BBB_SWITCH_B;

--============= EPH Tables ============----
DROP TABLE BBB_MISC.BBB_SKU_EPH;

CREATE TABLE BBB_MISC.BBB_SKU_EPH
(
  SKU_ID  VARCHAR2(40) NOT NULL,
  EPH_PROD_NODE_ID VARCHAR2(40) NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_SKU_EPH_PK PRIMARY KEY(SKU_ID)  
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_SKU_EPH TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_SKU_EPH TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_SKU_EPH TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_SKU_EPH TO BBB_SWITCH_B;

-- ROLLUP OF EPH DATA TO PRODUCT LEVEL
DROP TABLE BBB_MISC.BBB_PRODUCT_EPH;

CREATE TABLE BBB_MISC.BBB_PRODUCT_EPH
(
	PRODUCT_ID				VARCHAR2(40) NOT NULL,
	EPH_PROD_NODE_ID		VARCHAR2(40) NOT NULL,
	CREATE_USER VARCHAR2(40) NOT NULL,
	CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
	LAST_MOD_USER VARCHAR2(40) NOT NULL,
	LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
	CONSTRAINT BBB_SKU_EPH_PK PRIMARY KEY(PRODUCT_ID)  
);

GRANT SELECT ON BBB_MISC.BBB_PRODUCT_EPH TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_PRODUCT_EPH TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_PRODUCT_EPH TO bbb_switch_a;
GRANT SELECT ON BBB_MISC.BBB_PRODUCT_EPH TO bbb_switch_b;


DROP TABLE BBB_MISC.BBB_EPH_NODE;

CREATE TABLE BBB_MISC.BBB_EPH_NODE
(
  EPH_NODE_ID VARCHAR2(40) NOT NULL,
  DISPLAY_NAME VARCHAR2(254) NOT NULL,
  IS_ROOT_NODE NUMBER(1,0) NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_EPH_NODE_PK PRIMARY KEY(EPH_NODE_ID)    
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_EPH_NODE TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_EPH_NODE TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_EPH_NODE TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_EPH_NODE TO BBB_SWITCH_B;


DROP TABLE BBB_MISC.BBB_EPH_NODE_PARENT;

CREATE TABLE BBB_MISC.BBB_EPH_NODE_PARENT
(
  PARENT_NODE_ID  VARCHAR2(40) NOT NULL,
  CHILD_NODE_ID VARCHAR2(40) NOT NULL,
  CREATE_USER VARCHAR2(40) NOT NULL,
  CREATE_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  LAST_MOD_USER VARCHAR2(40) NOT NULL,
  LAST_MOD_DATE TIMESTAMP(6) DEFAULT SYSDATE NOT NULL,
  CONSTRAINT BBB_EPH_NODE_PARENT_PK PRIMARY KEY(CHILD_NODE_ID,PARENT_NODE_ID)
);

-- ######  NEED GRANTS FOR ALL USERS  ######
GRANT SELECT ON BBB_MISC.BBB_EPH_NODE_PARENT TO BBB_RO;
GRANT SELECT ON BBB_MISC.BBB_EPH_NODE_PARENT TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_EPH_NODE_PARENT TO BBB_SWITCH_A;
GRANT SELECT ON BBB_MISC.BBB_EPH_NODE_PARENT TO BBB_SWITCH_B;

/*
--####### GRANTS FOR ADMIN UI  ######
GRANT SELECT ON BBB_MISC.BBB_LIST_TYPE TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CHLDCAT TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CATEGORY TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_CHLDCAT TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_EPH_FACETS TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_JDA TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_EPH TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_CAT_FACET TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_FACET_RULES TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_LIST_PKG_CNT_FACETS TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_SKU_COMPUTED_ATTRIBUTES TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_SKU_EPH TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_EPH_NODE TO ECOMWEB;
GRANT SELECT ON BBB_MISC.BBB_EPH_NODE_PARENT TO ECOMWEB;
*/
