-- drop table BBB_CHAT_ATTRIBUTES;

CREATE TABLE BBB_CHAT_ATTRIBUTES (
	id 			varchar2(254)	NOT NULL REFERENCES site_configuration(id),
	chat_URL 		varchar2(254)	NULL,
	ONOFF_FLAG 		number(1)	NULL,
	WEEKDAY_OPENTIME 	DATE	NULL,
	WEEKDAY_CLOSETIME 	DATE	NULL,
	WEEKEND_OPENTIME 	DATE	NULL,
	WEEKEND_CLOSETIME 	DATE	NULL,
	PRIMARY KEY(id)
);
