CREATE INDEX BBB_SITE_ATTRIBUTES_idx ON BBB_SITE_ATTRIBUTES(id);

CREATE INDEX BBB_APPLICABLE_SHIP_METDS_idx ON BBB_APPLICABLE_SHIP_METHODS(id, ship_method_cd);

CREATE INDEX BBB_STATES_LIST_idx ON BBB_STATES_LIST(id, state_id);

CREATE INDEX BBB_NEXUS_STATES_idx ON BBB_NEXUS_STATES(id, state_id);

CREATE INDEX BBB_REG_TP_ST_MAPPINGS_idx ON BBB_REGISTRY_TYPE_SITE_MAPPINGS(id, registry_type_id);

CREATE INDEX BBB_APPB_PMNT_CARDS_idx ON BBB_APPLICABLE_PAYMENT_CARDS(id, payment_card_id);

CREATE INDEX BBB_TIME_ZONE_LIST_idx ON BBB_TIME_ZONE_LIST(id, time_zone_id);