//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.11 at 01:38:02 PM IST 
//


package com.bbb.account.baby;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BABYBOOKREQUEST complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BABYBOOKREQUEST">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TYPE" type="{}TypeEnum"/>
 *         &lt;element name="FIRST_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LAST_NM" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADDR1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADDR2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CITY" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="STATE_CD" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ZIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DAY_PHONE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EMAIL_ADDR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EVENT_DATE" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="EMAIL_OFFER" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="SUBMIT_DT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="SITE_FLAG" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BABYBOOKREQUEST", propOrder = {
    "type",
    "firstnm",
    "lastnm",
    "addr1",
    "addr2",
    "city",
    "statecd",
    "zip",
    "dayphone",
    "emailaddr",
    "eventdate",
    "emailoffer",
    "submitdt",
    "siteflag"
})
public class BABYBOOKREQUEST {

    @XmlElement(name = "TYPE", required = true)
    protected TypeEnum type;
    @XmlElement(name = "FIRST_NM", required = true)
    protected String firstnm;
    @XmlElement(name = "LAST_NM", required = true)
    protected String lastnm;
    @XmlElement(name = "ADDR1", required = true)
    protected String addr1;
    @XmlElement(name = "ADDR2")
    protected String addr2;
    @XmlElement(name = "CITY", required = true)
    protected String city;
    @XmlElement(name = "STATE_CD", required = true)
    protected String statecd;
    @XmlElement(name = "ZIP", required = true)
    protected String zip;
    @XmlElement(name = "DAY_PHONE", required = true)
    protected String dayphone;
    @XmlElement(name = "EMAIL_ADDR")
    protected String emailaddr;
    @XmlElement(name = "EVENT_DATE")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventdate;
    @XmlElement(name = "EMAIL_OFFER")
    protected Boolean emailoffer;
    @XmlElement(name = "SUBMIT_DT", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar submitdt;
    @XmlElement(name = "SITE_FLAG", required = true)
    protected String siteflag;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TypeEnum }
     *     
     */
    public TypeEnum getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeEnum }
     *     
     */
    public void setTYPE(TypeEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the firstnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRSTNM() {
        return firstnm;
    }

    /**
     * Sets the value of the firstnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRSTNM(String value) {
        this.firstnm = value;
    }

    /**
     * Gets the value of the lastnm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTNM() {
        return lastnm;
    }

    /**
     * Sets the value of the lastnm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTNM(String value) {
        this.lastnm = value;
    }

    /**
     * Gets the value of the addr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDR1() {
        return addr1;
    }

    /**
     * Sets the value of the addr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDR1(String value) {
        this.addr1 = value;
    }

    /**
     * Gets the value of the addr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADDR2() {
        return addr2;
    }

    /**
     * Sets the value of the addr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADDR2(String value) {
        this.addr2 = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCITY() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCITY(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the statecd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATECD() {
        return statecd;
    }

    /**
     * Sets the value of the statecd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATECD(String value) {
        this.statecd = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZIP() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZIP(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the dayphone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDAYPHONE() {
        return dayphone;
    }

    /**
     * Sets the value of the dayphone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDAYPHONE(String value) {
        this.dayphone = value;
    }

    /**
     * Gets the value of the emailaddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAILADDR() {
        return emailaddr;
    }

    /**
     * Sets the value of the emailaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAILADDR(String value) {
        this.emailaddr = value;
    }

    /**
     * Gets the value of the eventdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEVENTDATE() {
        return eventdate;
    }

    /**
     * Sets the value of the eventdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEVENTDATE(XMLGregorianCalendar value) {
        this.eventdate = value;
    }

    /**
     * Gets the value of the emailoffer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEMAILOFFER() {
        return emailoffer;
    }

    /**
     * Sets the value of the emailoffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEMAILOFFER(Boolean value) {
        this.emailoffer = value;
    }

    /**
     * Gets the value of the submitdt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSUBMITDT() {
        return submitdt;
    }

    /**
     * Sets the value of the submitdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSUBMITDT(XMLGregorianCalendar value) {
        this.submitdt = value;
    }

    /**
     * Gets the value of the siteflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSITEFLAG() {
        return siteflag;
    }

    /**
     * Sets the value of the siteflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSITEFLAG(String value) {
        this.siteflag = value;
    }

}
