//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.11 at 01:38:02 PM IST 
//


package com.bbb.account.baby;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DATA_RECORD" type="{}BABYBOOKREQUEST"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datarecord"
})
@XmlRootElement(name = "main")
public class Main {

    @XmlElement(name = "DATA_RECORD", required = true)
    protected BABYBOOKREQUEST datarecord;

    /**
     * Gets the value of the datarecord property.
     * 
     * @return
     *     possible object is
     *     {@link BABYBOOKREQUEST }
     *     
     */
    public BABYBOOKREQUEST getDATARECORD() {
        return datarecord;
    }

    /**
     * Sets the value of the datarecord property.
     * 
     * @param value
     *     allowed object is
     *     {@link BABYBOOKREQUEST }
     *     
     */
    public void setDATARECORD(BABYBOOKREQUEST value) {
        this.datarecord = value;
    }

}
