SET DEFINE OFF;

drop table BBB_PICKLIST_SKUS;

drop table  BBB_PICKLIST_CHANNELS;

drop table BBB_PICKLIST_REG_TYPES;

drop table BBB_KICK_STARTER_PICKLISTS;

drop table BBB_KICK_STARTER_PICKLIST;

drop table BBB_KICK_STARTER;

drop table BBB_PICKLIST_SKU_ITEM;

drop table  BBB_KICK_START_REG_TYPE_BADGE;

COMMIT;